In [1]:
import numpy as np
a=np.array([[1,2.0,3],[1,2,7]], dtype='int64')
b=np.array([1,3,5])

In [2]:
a.shape

(2, 3)

In [3]:
a.dtype

dtype('int64')

In [4]:
a.itemsize#for calculating total no.of bytes 

8

In [5]:
a.nbytes# total no of bytes of an entire array


48

In [6]:
d=9

In [7]:
d

9

In [8]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [9]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [10]:
a[0,1:4:2]#1 is the starting one 4 is the ending one and 2 is the step size

array([2, 4])

In [11]:
a[0:2]#it prints from zeroth row o 1st column 2is exclusive

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [12]:
a[1:,2]=5#it makes value 5 for from starting row to last row of all 2nd index values to 5

In [13]:
a#in the above command before comma it will take rows and after comma it takes columns

array([[1, 2, 3, 4, 5],
       [6, 7, 5, 9, 0]])

In [14]:
a[:,1]=999

In [15]:
a

array([[  1, 999,   3,   4,   5],
       [  6, 999,   5,   9,   0]])

In [16]:
np.zeros((2,2,3))#1st 2 wil print 2 subarrays and 2nd 2 is for no of rows in subarrays and 3 is for no of col

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
a=np.ones((2,2),dtype='int32')

In [19]:
a#here by default it will print all 1. 1. ie is all float so converted it into int

array([[1, 1],
       [1, 1]])

In [20]:
np.full((2,2),3, dtype='int32') #here we can make total array of 99 1st parenthisi is the shape and 2nd is the number which we need to get

array([[3, 3],
       [3, 3]])

In [21]:
np.full((3,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
np.random.rand(2,3)

array([[0.99349319, 0.68038851, 0.91055359],
       [0.75858633, 0.5083729 , 0.3839477 ]])

In [23]:
#random of integers
np.random.randint(7,size=(2,3))
#it creates random integers from 0 to 7 of size 2,3

array([[3, 3, 6],
       [3, 5, 4]])

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a=np.ones((5,5), dtype='int32')
print(a)
z=np.zeros((3,3), dtype='int32')
z[1,1]=9
print(z)
a[1:4,1:4]=z
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# be careful when copying arrays!!!


In [26]:
a=np.array([1,2,3])
print(a)
b=a
b[0]=100
print(a)

[1 2 3]
[100   2   3]


In [27]:
#so to avoid this thing
a=np.array([1,2,3])
print(a)
b=a.copy()
b[0]=100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


In [28]:
a+2#adds 2 to every element

array([3, 4, 5])

In [29]:
a-2

array([-1,  0,  1])

In [30]:
a


array([1, 2, 3])

In [31]:
b=np.array([5,6,7])

In [32]:
a+b

array([ 6,  8, 10])

In [33]:
np.sin(a)#sin of all values of a 

array([0.84147098, 0.90929743, 0.14112001])

In [34]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [35]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [36]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [37]:
#in the above one we cannot make a*b it makes normal mult but we can perforem matrix mult

In [38]:
np.matmul(a,b)#we wil end up with a 2,2 matrix

array([[6., 6.],
       [6., 6.]])

In [39]:
a=np.identity(4)
np.linalg.det(a)
#to find det

1.0

In [40]:
np.sum(a)#sum of all elements of the array

4.0

In [41]:
a=np.array([[1,2,3,4,],[6,7,8,9]])
np.min(a)


1

In [42]:
np.max(a)

9

In [43]:
np.max(a,axis=1)#it gives max elements from all rows

array([4, 9])

In [44]:
np.max(a,axis=0)#it gives max elements from all colums of the arry

array([6, 7, 8, 9])

In [45]:
np.sum(a,axis=0)

array([ 7,  9, 11, 13])

# reorganizing the arrays

In [46]:
before=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(before)
after=before.reshape(5,2)

print(after)
#the orginal shape have to fit the reshaped one

[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [47]:
q=np.array([1,2,3,4,])
s=np.array([9,8,7,6])
np.vstack([q,s,q,s])
#it adds rows in vetical

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [1, 2, 3, 4],
       [9, 8, 7, 6]])

In [48]:
np.hstack((q,s))#it adds horizontally

array([1, 2, 3, 4, 9, 8, 7, 6])

In [49]:
q>50#it returns true if values of array are greater than 50

array([False, False, False, False])